# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170821_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plug_ins',
            new_name='type',
        ),
    ]
