# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170821_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='time',
        ),
    ]
