# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(max_length=2000)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApprovalStatus', models.CharField(choices=[('AP', '正式社员'), ('WL', '等候列表'), ('NA', '非社员'), ('NV', '未审核')], default='NV', max_length=2)),
                ('Member_type', models.CharField(choices=[('PR', '社长'), ('VP', '副社长'), ('FM', '财务'), ('CS', '社团核心成员'), ('MB', '社团')], default='MB', max_length=2)),
                ('club_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
