# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='time',
        ),
        migrations.AddField(
            model_name='club',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
