# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EventPhotographerAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_photographer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=1000)),
                ('assignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.EventPhotographerAssigned')),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField(default=0)),
                ('class_in', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='eventphotographerassigned',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Events'),
        ),
        migrations.AddField(
            model_name='eventfileupload',
            name='assignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.EventPhotographerAssigned'),
        ),
    ]
